spring:
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8090



application:
  config:
    membership-type-url: http://localhost:8222/api/v1/membership-types
    membership-url: http://localhost:8222/api/v1/memberships
    member-url: http://localhost:8222/api/v1/members
    role-url: http://localhost:8222/api/v1/roles

aws:
  s3:
    access:
      key: AKIAT4GVRMTPBTFGNH77
    secret:
      key: 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
    region: eu-north-1
    bucket: arjay-fileupload

jwt:
  secret: "TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V"
  expiration: 3600000