spring:
  application:
    name: organization-service
  profiles:
    active: prod  # This activates the 'dev' profile for this service
  config:
    import: optional:configserver:http://localhost:8888

